from langsmith import traceable
from langchain_core.messages import HumanMessage
from langgraph.graph import StateGraph, START, END
from langgraph.prebuilt import tools_condition

# Import the state schema
from app.agent.state import AgentState

# Import the isolated execution nodes (this prevents circular dependencies)
from app.agent.nodes import call_model, tool_node

# =========================================================
# 1. GRAPH TOPOLOGY & COMPILATION
# =========================================================

# Initialize the stateful workflow
workflow = StateGraph(AgentState)

# Register the execution nodes
workflow.add_node("agent", call_model)
workflow.add_node("tools", tool_node)

# Set the entry point to always hit the LLM first
workflow.add_edge(START, "agent")

# Native router: evaluates if the AI populated the scratchpad with a ToolCall
workflow.add_conditional_edges("agent", tools_condition)

# Hardwire the tools to always loop back to the agent to read results
workflow.add_edge("tools", "agent")

# Compile the executable application
agent_app = workflow.compile()

# =========================================================
# 2. INVOCATION HELPER (Called by FastAPI Route)
# =========================================================

@traceable
async def invoke_agent(user_message: str) -> str:
    """
    Handles state initialization and triggers the compiled LangGraph execution loop.
    Call this directly from your FastAPI route.
    """
    # Pack the user's text into the initial graph state
    initial_state = {
        "messages": [HumanMessage(content=user_message)]
    }

    # CRITICAL FIX: Await the compiled graph (agent_app), NOT just the single node.
    # This starts the actual execution engine and tool-calling loop.
    final_state = await agent_app.ainvoke(initial_state)
    
    # Extract and return the very last text response generated by the AI
    return final_state["messages"][-1].content