from langgraph.graph import StateGraph, START, END
from langgraph.prebuilt import tools_condition

# Import your State and Nodes from across your project
from app.agent.state import AgentState
from app.agent.nodes import initialize_context, call_model, tool_node, save_memory


def agent_graph():
    """
    Constructs and wires the deterministic routing for the HR Leave Agent.
    """
    # 1. Initialize the Graph Builder with our strict TypedDict schema
    builder = StateGraph(AgentState)

    # 2. Register all Nodes (The Execution Engines)
    builder.add_node("initialize_context", initialize_context) # Node 1: Hydration
    builder.add_node("call_model", call_model)                 # Node 2: Reasoning
    builder.add_node("tool_node", tool_node)               # Node 3: Backend Actions
    builder.add_node("save_memory", save_memory)               # Node 4: Persistence

    # 3. Define the Ingestion Flow
    # The graph wakes up and immediately pulls the database history
    builder.add_edge(START, "initialize_context")
    
    # Once hydrated, it always passes the state to the LLM to think
    builder.add_edge("initialize_context", "call_model")

    # 4. The Fail-Proof Conditional Routing
    # `tools_condition` safely inspects the AIMessage generated by Node 2.
    # We map its strict outputs ("tools" or "__end__") to our custom nodes.
    builder.add_conditional_edges(
        "call_model",
        tools_condition, 
        {
            "tools": "tool_node",  # If LLM wants to check balance/submit leave
            "__end__": "save_memory"   # If LLM is finished and replying to the user
        }
    )

    # 5. The Tool Loop
    # After a backend tool executes, it must always return to the LLM 
    # so the model can read the database result and formulate an answer.
    builder.add_edge("tool_node", "call_model")

    # 6. The Exit Strategy
    # Once Node 4 successfully pushes the pruned history to MySQL, shut the graph down.
    builder.add_edge("save_memory", END)

    # 7. Compile the application
    # By default, LangGraph sets a recursion_limit (usually 25). If the model gets stuck 
    # in an infinite loop failing to use a tool, the framework halts it automatically.
    return builder.compile()

# This is the compiled object your FastAPI route will import and invoke
agent_app = agent_graph()